name: Backend-Build CI

on:
  push:
    branches:
      - main
    paths:
      - 'car-rental-spring/**'
  pull_request:
    branches:
      - main
    paths:
      - 'car-rental-spring/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: car-rental-spring
