name: Backend-Build CI

on:
  push:
    branches:
      - main
    paths:
      - 'car-rental-spring/**'
  pull_request:
    branches:
      - main
    paths:
      - 'car-rental-spring/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: car-rental-spring

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Maven Installation
        run: mvn -v

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test
