name: Backend-Build CI

on: 
  push: 
    branches:
      - 'car-rental-spring/**'
  
  pull_request:
    branches:
      - 'car-rental-spring/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
  

